apiVersion: v1
kind: Service
metadata:
  name: sensor-relay
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sensor-relay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-relay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensor-relay
  template:
    metadata:
      labels:
        app: sensor-relay
    spec:
      containers:
      - image: $DOCKER_IMAGE
        imagePullPolicy: Always
        name: sensor-relay-container
